insert
    my_warehouse.dleivery_list(id_del,
                               id_product_info,
                               preice_per_unit,
                               quantity)
    values('$id_del',
           '$id_product_info',
           '$preice_per_unit',
           '$quantity')